import type { Weapon } from "../../types/weapon/weapon";

export const merylIronheart = {
  id: "Meryl Ironheart",
  displayName: "Meryl Ironheart",
  elementalIcon: "Volt-Frost",
  resonanceElements: ["Volt", "Frost"],
  calculationElements: ["Volt", "Frost"],
  damageElement: "Volt",
  type: "Defense",
  attackPercentBuffs: [
    {
      id: "Volt Resonance",
      displayName: "Volt Resonance",
      description: "+15% volt ATK when equipping 2 or more volt weapons",
      value: 0.15,
      elementalTypes: ["Volt"],
      canStack: false,
      isActivePassively: true,
      minStarRequirement: 0,
      maxStarRequirement: 6,
      elementalResonanceRequirements: ["Volt"],
    },
    {
      id: "Frost Resonance",
      displayName: "Frost Resonance",
      description: "+15% frost ATK when equipping 2 or more frost weapons",
      value: 0.15,
      elementalTypes: ["Frost"],
      canStack: false,
      isActivePassively: true,
      minStarRequirement: 0,
      maxStarRequirement: 6,
      elementalResonanceRequirements: ["Frost"],
    },
    {
      id: "Meryl Ironheart Discharge ATK Buff",
      displayName: "Meryl Ironheart discharge",
      description: "+10% volt ATK for 20s on Meryl Ironheart discharge",
      value: 0.1,
      elementalTypes: ["Volt"],
      canStack: false,
      isActivePassively: false,
      minStarRequirement: 0,
      maxStarRequirement: 6,
    },
  ],
  critRateBuffs: [],
  critDamageBuffs: [],
  normalAttacks: [],
  dodgeAttacks: [],
  skills: [],
  discharges: [],
  buffs: [],
  resources: [],
} as const satisfies Weapon;
