import type { Weapon } from '../../types/weapon/weapon';
import { nolaBase } from './nola-base';

export const nolaVoltFrost = {
  ...nolaBase,
  id: 'Nola (Volt-Frost)',
  displayName: 'Nola (Volt-Frost)',
  elementalIcon: 'Volt-Frost',
  resonanceElements: ['Volt', 'Frost'],
  calculationElements: ['Volt', 'Frost'],
  damageElement: 'Volt',
  attackPercentBuffs: [
    ...nolaBase.attackPercentBuffs,
    {
      id: 'Volt Resonance',
      displayName: 'Volt Resonance',
      description: '+15% volt ATK when equipping 2 or more volt weapons',
      value: 0.15,
      elementalTypes: ['Volt'],
      canStack: false,
      isActivePassively: true,
      minStarRequirement: 0,
      maxStarRequirement: 6,
      elementalResonanceRequirements: ['Volt'],
    },
    {
      id: 'Frost Resonance',
      displayName: 'Frost Resonance',
      description: '+15% frost ATK when equipping 2 or more frost weapons',
      value: 0.15,
      elementalTypes: ['Frost'],
      canStack: false,
      isActivePassively: true,
      minStarRequirement: 0,
      maxStarRequirement: 6,
      elementalResonanceRequirements: ['Frost'],
    },
  ],
  critRateBuffs: [...nolaBase.critRateBuffs],
  critDamageBuffs: [...nolaBase.critDamageBuffs],
  normalAttacks: [...nolaBase.normalAttacks],
  dodgeAttacks: [...nolaBase.dodgeAttacks],
  skills: [...nolaBase.skills],
  discharges: [...nolaBase.discharges],
  buffs: [...nolaBase.buffs],
  resources: [...nolaBase.resources],
} as const satisfies Weapon;
