import type { PartialWeaponDefinition } from "../../types/weapon/partial-weapon-definition";

export const salidy = {
  id: "Salidy",
  simulacrumDisplayName: "Salidy",
  weaponDisplayName: "Bloodfin",
  elementalIcon: "Flame-Physical",
  resonanceElements: ["Flame", "Physical"],
  gearResonanceElements: ["Flame", "Physical"],
  damageElement: "Flame",
  type: "DPS",

  normalAttacks: [],
  dodgeAttacks: [],
  skills: [],
  discharges: [],

  buffs: [
    {
      id: "Salidy 1*",
      displayName: "Salidy 1*",
      description: "Increases Flame Damage by 8%",
      cooldown: 0,
      requirements: {},
      canBePlayerTriggered: false,
      triggeredBy: { combatStart: true },
      maxStacks: 1,
      elementalDamageBuffs: [{ value: 0.08, elementalTypes: ["Flame"] }],
      starRequirement: { minStarRequirement: 1, maxStarRequirement: 6 },
    },
    {
      id: "Salidy 3*",
      displayName: "Salidy 3*",
      description: "Increases Flame Damage by 3%",
      cooldown: 0,
      requirements: {},
      canBePlayerTriggered: false,
      triggeredBy: { combatStart: true },
      maxStacks: 1,
      elementalDamageBuffs: [{ value: 0.03, elementalTypes: ["Flame"] }],
      starRequirement: { minStarRequirement: 3, maxStarRequirement: 6 },
    },
    {
      id: "Salidy 5*",
      displayName: "Salidy 5*",
      description: "Increases Final Damage by 8%",
      cooldown: 0,
      requirements: {},
      canBePlayerTriggered: false,
      triggeredBy: { combatStart: true },
      maxStacks: 1,
      finalDamageBuffs: [{ value: 0.08 }],
      starRequirement: { minStarRequirement: 5, maxStarRequirement: 6 },
    },
    {
      id: "Salidy 6*",
      displayName: "Salidy 6*",
      description: "Increases Final Damage by 28% and Flame Damage by 8%",
      cooldown: 0,
      requirements: {},
      canBePlayerTriggered: false,
      triggeredBy: { combatStart: true },
      maxStacks: 1,
      elementalDamageBuffs: [{ value: 0.08, elementalTypes: ["Flame"] }],
      finalDamageBuffs: [{ value: 0.28 }],
      starRequirement: { minStarRequirement: 6, maxStarRequirement: 6 },
    },
  ],
  resources: [],
} as const satisfies PartialWeaponDefinition;
