import type { Data } from '../models/data';
import type { GearType } from '../models/gear-type';
import { GearName, GearVersion } from '../models/gear-type';
import { StatName } from '../models/stat-type';

export const gearTypesLookup: Data<GearName, GearType> = {
  allIds: [
    GearName.Helmet,
    GearName.Eyepiece,
    GearName.Spaulders,
    GearName.Gloves,
    GearName.Bracers,
    GearName.Armor,
    GearName.CombatEngine,
    GearName.Belt,
    GearName.Legguards,
    GearName.Boots,
    GearName.Exoskeleton,
    GearName.Microreactor,
  ],
  byId: {
    [GearName.Helmet]: {
      id: GearName.Helmet,
      displayName: GearName.Helmet,
      inGameName: 'Helm',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
      ],
      version: GearVersion.v1,
    },
    [GearName.Eyepiece]: {
      id: GearName.Eyepiece,
      displayName: GearName.Eyepiece,
      inGameName: 'Eyepiece',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.HPPercent,
        StatName.CritRatePercent,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.AlteredAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
        StatName.AlteredResistance,
        StatName.PhysicalAttackPercent,
        StatName.FlameAttackPercent,
        StatName.FrostAttackPercent,
        StatName.VoltAttackPercent,
        StatName.PhysicalResistancePercent,
        StatName.FrostResistancePercent,
        StatName.FlameResistancePercent,
        StatName.VoltResistancePercent,
        StatName.AlteredResistancePercent,
      ],
      version: GearVersion.v1,
    },
    [GearName.Spaulders]: {
      id: GearName.Spaulders,
      displayName: GearName.Spaulders,
      inGameName: 'Spaulders',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
      ],
      version: GearVersion.v1,
    },
    [GearName.Gloves]: {
      id: GearName.Gloves,
      displayName: GearName.Gloves,
      inGameName: 'Handguards',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Crit,
        StatName.Attack,
        StatName.Resistance,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
      ],
      version: GearVersion.v1,
    },
    [GearName.Bracers]: {
      id: GearName.Bracers,
      displayName: GearName.Bracers,
      inGameName: 'Bracers',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
      ],
      version: GearVersion.v1,
    },
    [GearName.Armor]: {
      id: GearName.Armor,
      displayName: GearName.Armor,
      inGameName: 'Armor',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
      ],
      version: GearVersion.v1,
    },
    [GearName.CombatEngine]: {
      id: GearName.CombatEngine,
      displayName: GearName.CombatEngine,
      inGameName: 'Combat Engine',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.HPPercent,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
        StatName.PhysicalAttackPercent,
        StatName.FlameAttackPercent,
        StatName.FrostAttackPercent,
        StatName.VoltAttackPercent,
        StatName.PhysicalResistancePercent,
        StatName.FrostResistancePercent,
        StatName.FlameResistancePercent,
        StatName.VoltResistancePercent,
        StatName.PhysicalDamagePercent,
        StatName.FlameDamagePercent,
        StatName.FrostDamagePercent,
        StatName.VoltDamagePercent,
      ],
      version: GearVersion.v2,
    },
    [GearName.Belt]: {
      id: GearName.Belt,
      displayName: GearName.Belt,
      inGameName: 'Belt',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
      ],
      version: GearVersion.v1,
    },
    [GearName.Legguards]: {
      id: GearName.Legguards,
      displayName: GearName.Legguards,
      inGameName: 'Legguards',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
      ],
      version: GearVersion.v1,
    },
    [GearName.Boots]: {
      id: GearName.Boots,
      displayName: GearName.Boots,
      inGameName: 'Sabatons',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Crit,
        StatName.Attack,
        StatName.Resistance,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
      ],
      version: GearVersion.v1,
    },
    [GearName.Exoskeleton]: {
      id: GearName.Exoskeleton,
      displayName: GearName.Exoskeleton,
      inGameName: 'Exoskeleton',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.HPPercent,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
        StatName.PhysicalAttackPercent,
        StatName.FlameAttackPercent,
        StatName.FrostAttackPercent,
        StatName.VoltAttackPercent,
        StatName.PhysicalResistancePercent,
        StatName.FrostResistancePercent,
        StatName.FlameResistancePercent,
        StatName.VoltResistancePercent,
        StatName.PhysicalDamagePercent,
        StatName.FlameDamagePercent,
        StatName.FrostDamagePercent,
        StatName.VoltDamagePercent,
      ],
      version: GearVersion.v2,
    },
    [GearName.Microreactor]: {
      id: GearName.Microreactor,
      displayName: GearName.Microreactor,
      inGameName: 'Microreactor',
      numberOfRandomStats: 4,
      possibleRandomStatTypeIds: [
        StatName.HP,
        StatName.Attack,
        StatName.Resistance,
        StatName.HPPercent,
        StatName.PhysicalAttack,
        StatName.FrostAttack,
        StatName.FlameAttack,
        StatName.VoltAttack,
        StatName.PhysicalResistance,
        StatName.FrostResistance,
        StatName.FlameResistance,
        StatName.VoltResistance,
        StatName.PhysicalAttackPercent,
        StatName.FlameAttackPercent,
        StatName.FrostAttackPercent,
        StatName.VoltAttackPercent,
        StatName.PhysicalResistancePercent,
        StatName.FrostResistancePercent,
        StatName.FlameResistancePercent,
        StatName.VoltResistancePercent,
        StatName.PhysicalDamagePercent,
        StatName.FlameDamagePercent,
        StatName.FrostDamagePercent,
        StatName.VoltDamagePercent,
      ],
      version: GearVersion.v2,
    },
  },
};
