import type { Data } from '../models/data';
import type { WeaponDefinition } from '../models/weapon-definition';

export type WeaponName =
  | 'Alyss'
  | 'Annabella'
  | 'Claudia'
  | 'Cobalt-B'
  | 'Cocoritter'
  | 'Crow'
  | 'Fenrir'
  | 'Fiona'
  | 'Frigg'
  | 'Gnonno'
  | 'Huang (Mimi)'
  | 'Huma'
  | 'Icarus'
  | 'King'
  | 'Lan'
  | 'Lin'
  | 'Liu Huo'
  | 'Lyra'
  | 'Meryl'
  | 'Ming Jing'
  | 'Nemesis'
  | 'Rubilia'
  | 'Ruby'
  | 'Saki Fuwa'
  | 'Samir'
  | 'Shiro'
  | 'Tian Lang'
  | 'Tsubasa'
  | 'Umi'
  | 'Yu Lan'
  | 'Zero';

export const weaponDefinitions: Data<WeaponName, WeaponDefinition> = {
  allIds: [
    'Alyss',
    'Annabella',
    'Claudia',
    'Cobalt-B',
    'Cocoritter',
    'Crow',
    'Fenrir',
    'Fiona',
    'Frigg',
    'Gnonno',
    'Huang (Mimi)',
    'Huma',
    'Icarus',
    'King',
    'Lan',
    'Lin',
    'Liu Huo',
    'Lyra',
    'Meryl',
    'Ming Jing',
    'Nemesis',
    'Rubilia',
    'Ruby',
    'Saki Fuwa',
    'Samir',
    'Shiro',
    'Tian Lang',
    'Tsubasa',
    'Umi',
    'Yu Lan',
    'Zero',
  ],
  byId: {
    ['Alyss']: {
      id: 'Alyss',
      displayName: 'Alyss',
      elementalType: 'Frost',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Frost Resonance',
          displayName: 'Frost Resonance',
          description: '+15% frost ATK when equipping 2 or more frost weapons',
          value: 0.15,
          elementalTypes: ['Frost'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Frost'],
        },
      ],
      critRateBuffs: [],
    },
    ['Annabella']: {
      id: 'Annabella',
      displayName: 'Annabella',
      elementalType: 'Flame',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Flame Resonance',
          displayName: 'Flame Resonance',
          description: '+15% flame ATK when equipping 2 or more flame weapons',
          value: 0.15,
          elementalTypes: ['Flame'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Flame'],
        },
      ],
      critRateBuffs: [
        {
          id: 'Tranquil Heart',
          displayName: 'Tranquil Heart',
          description:
            'Tranquil Heart: after using discharge/skill/dodge/charge attack, increase crit rate by 5%, stacking up to 3 times. Lasts for 15s.',
          value: 0.15,
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 0,
          maxStarRequirement: 2,
        },
        {
          id: 'Tranquil Heart',
          displayName: 'Tranquil Heart',
          description:
            'Tranquil Heart: after using discharge/skill/dodge/charge attack, increase crit rate by 9%, stacking up to 3 times. Lasts for 15s.',
          value: 0.27,
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 3,
          maxStarRequirement: 6,
        },
      ],
    },
    ['Claudia']: {
      id: 'Claudia',
      displayName: 'Claudia',
      elementalType: 'Physical',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Physical Resonance',
          displayName: 'Physical Resonance',
          description:
            '+15% physical ATK when equipping 2 or more physical weapons',
          value: 0.15,
          elementalTypes: ['Physical'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Physical'],
        },
      ],
      critRateBuffs: [],
    },
    ['Cobalt-B']: {
      id: 'Cobalt-B',
      displayName: 'Cobalt-B',
      elementalType: 'Flame',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Flame Resonance',
          displayName: 'Flame Resonance',
          description: '+15% flame ATK when equipping 2 or more flame weapons',
          value: 0.15,
          elementalTypes: ['Flame'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Flame'],
        },
      ],
      critRateBuffs: [],
    },
    ['Cocoritter']: {
      id: 'Cocoritter',
      displayName: 'Cocoritter',
      elementalType: 'Frost',
      type: 'Support',
      attackPercentBuffs: [
        {
          id: 'Frost Resonance',
          displayName: 'Frost Resonance',
          description: '+15% frost ATK when equipping 2 or more frost weapons',
          value: 0.15,
          elementalTypes: ['Frost'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Frost'],
        },
        {
          id: 'Frost Benediction',
          displayName: 'Frost Benediction',
          description:
            "+5% entire team's frost ATK by 5% when Benediction Resonance is active",
          value: 0.05,
          elementalTypes: ['Frost'],
          canStack: true,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          weaponResonanceRequirements: ['Benediction'],
        },
      ],
      critRateBuffs: [],
    },
    ['Crow']: {
      id: 'Crow',
      displayName: 'Crow',
      elementalType: 'Volt',
      type: 'DPS',
      attackPercentBuffs: [],
      critRateBuffs: [],
    },
    ['Fenrir']: {
      id: 'Fenrir',
      displayName: 'Fenrir',
      elementalType: 'Volt',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Volt Resonance',
          displayName: 'Volt Resonance',
          description: '+15% volt ATK when equipping 2 or more volt weapons',
          value: 0.15,
          elementalTypes: ['Volt'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Volt'],
        },
        {
          id: 'Elemental Balancing',
          displayName: 'Elemental Balancing',
          description:
            '+15% all ATK by equipping 3 weapons of different elements',
          value: 0.15,
          elementalTypes: ['Altered', 'Flame', 'Frost', 'Physical', 'Volt'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['None'],
        },
      ],
      critRateBuffs: [
        {
          id: 'Fenrir 6*',
          displayName: 'Fenrir 6*',
          description: 'Active when Fenrir is on-field + 5s off-field',
          value: 0.18,
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 6,
          maxStarRequirement: 6,
        },
      ],
    },
    ['Fiona']: {
      id: 'Fiona',
      displayName: 'Fiona',
      elementalType: 'Altered',
      type: 'Support',
      attackPercentBuffs: [
        {
          id: 'Altered Resonance',
          displayName: 'Altered Resonance',
          description: '+20% ATK when equipping 2 or more altered weapons',
          value: 0.2,
          elementalTypes: ['Altered', 'Flame', 'Frost', 'Physical', 'Volt'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Altered'],
        },
        {
          id: 'Fiona discharge',
          displayName: 'Fiona discharge',
          description: '+15% ATK for 30s on discharge',
          value: 0.15,
          elementalTypes: ['Altered', 'Flame', 'Frost', 'Physical', 'Volt'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          weaponResonanceRequirements: ['Attack', 'Balance'],
        },
      ],
      critRateBuffs: [],
    },
    ['Frigg']: {
      id: 'Frigg',
      displayName: 'Frigg',
      elementalType: 'Frost',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Frost Resonance',
          displayName: 'Frost Resonance',
          description: '+15% frost ATK when equipping 2 or more frost weapons',
          value: 0.15,
          elementalTypes: ['Frost'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Frost'],
        },
        {
          id: 'Frost Domain',
          displayName: 'Frost Domain',
          description: 'Frost Domain gives +15% frost ATK',
          value: 0.15,
          elementalTypes: ['Frost'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 0,
          maxStarRequirement: 5,
        },
        {
          id: 'Frost Domain',
          displayName: 'Frost Domain',
          description: 'Frost Domain gives +40% frost ATK',
          value: 0.4,
          elementalTypes: ['Frost'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 6,
          maxStarRequirement: 6,
        },
      ],
      critRateBuffs: [],
    },
    ['Gnonno']: {
      id: 'Gnonno',
      displayName: 'Gnonno',
      elementalType: 'Physical',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Physical Resonance',
          displayName: 'Physical Resonance',
          description:
            '+15% physical ATK when equipping 2 or more physical weapons',
          value: 0.15,
          elementalTypes: ['Physical'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Physical'],
        },
      ],
      critRateBuffs: [],
    },
    ['Huang (Mimi)']: {
      id: 'Huang (Mimi)',
      displayName: 'Huang (Mimi)',
      elementalType: 'Volt',
      type: 'Defense',
      attackPercentBuffs: [
        {
          id: 'Volt Resonance',
          displayName: 'Volt Resonance',
          description: '+15% volt ATK when equipping 2 or more volt weapons',
          value: 0.15,
          elementalTypes: ['Volt'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Volt'],
        },
      ],
      critRateBuffs: [],
    },
    ['Huma']: {
      id: 'Huma',
      displayName: 'Huma',
      elementalType: 'Flame',
      type: 'Defense',
      attackPercentBuffs: [],
      critRateBuffs: [],
    },
    ['Icarus']: {
      id: 'Icarus',
      displayName: 'Icarus',
      elementalType: 'Frost',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Frost Resonance',
          displayName: 'Frost Resonance',
          description: '+15% frost ATK when equipping 2 or more frost weapons',
          value: 0.15,
          elementalTypes: ['Frost'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Frost'],
        },
      ],
      critRateBuffs: [],
    },
    ['King']: {
      id: 'King',
      displayName: 'King',
      elementalType: 'Flame',
      type: 'DPS',
      attackPercentBuffs: [],
      critRateBuffs: [],
    },
    ['Lan']: {
      id: 'Lan',
      displayName: 'Lan',
      elementalType: 'Flame',
      type: 'Defense',
      attackPercentBuffs: [
        {
          id: 'Flame Resonance',
          displayName: 'Flame Resonance',
          description: '+15% flame ATK when equipping 2 or more flame weapons',
          value: 0.15,
          elementalTypes: ['Flame'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Flame'],
        },
      ],
      critRateBuffs: [],
    },
    ['Lin']: {
      id: 'Lin',
      displayName: 'Lin',
      elementalType: 'Altered',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Moonlight Realm',
          displayName: 'Moonlight Realm',
          description: 'Moonlight Realm gives +15% ATK for its duration',
          value: 0.15,
          elementalTypes: ['Altered', 'Flame', 'Frost', 'Physical', 'Volt'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 0,
          maxStarRequirement: 5,
        },
        {
          id: 'Moonlight Realm',
          displayName: 'Moonlight Realm',
          description: 'Moonlight Realm gives +23% ATK for its duration',
          value: 0.23,
          elementalTypes: ['Altered', 'Flame', 'Frost', 'Physical', 'Volt'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 6,
          maxStarRequirement: 6,
        },
        {
          id: 'Frost Moonlight Realm',
          displayName: 'Frost Moonlight Realm',
          description: 'Frost Moonlight Realm gives +10% frost ATK',
          value: 0.1,
          elementalTypes: ['Frost'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Frost'],
        },
        {
          id: 'Balance Moonlight Realm',
          displayName: 'Balance Moonlight Realm',
          description:
            'When paired with any 2 different elemental weapons, Moonlight Realm gives +15% ATK',
          value: 0.15,
          elementalTypes: ['Altered', 'Flame', 'Frost', 'Physical', 'Volt'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['None'],
        },
      ],
      critRateBuffs: [],
    },
    ['Liu Huo']: {
      id: 'Liu Huo',
      displayName: 'Liu Huo',
      elementalType: 'Flame',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Flame Resonance',
          displayName: 'Flame Resonance',
          description: '+15% flame ATK when equipping 2 or more flame weapons',
          value: 0.15,
          elementalTypes: ['Flame'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Flame'],
        },
      ],
      critRateBuffs: [],
    },
    ['Lyra']: {
      id: 'Lyra',
      displayName: 'Lyra',
      elementalType: 'Physical',
      type: 'Support',
      attackPercentBuffs: [
        {
          id: 'Physical Resonance',
          displayName: 'Physical Resonance',
          description:
            '+15% physical ATK when equipping 2 or more physical weapons',
          value: 0.15,
          elementalTypes: ['Physical'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Physical'],
        },
        {
          id: 'Physical Benediction',
          displayName: 'Physical Benediction',
          description:
            "+5% entire team's physical ATK by 5% when Benediction Resonance is active",
          value: 0.05,
          elementalTypes: ['Physical'],
          canStack: true,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          weaponResonanceRequirements: ['Benediction'],
        },
      ],
      critRateBuffs: [],
    },
    ['Meryl']: {
      id: 'Meryl',
      displayName: 'Meryl',
      elementalType: 'Frost',
      type: 'Defense',
      attackPercentBuffs: [],
      critRateBuffs: [],
    },
    ['Ming Jing']: {
      id: 'Ming Jing',
      displayName: 'Ming Jing (Zeke)',
      elementalType: 'Physical',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Physical Resonance',
          displayName: 'Physical Resonance',
          description:
            '+15% physical ATK when equipping 2 or more physical weapons',
          value: 0.15,
          elementalTypes: ['Physical'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Physical'],
        },
        {
          id: 'Flame Resonance',
          displayName: 'Flame Resonance',
          description: '+15% flame ATK when equipping 2 or more flame weapons',
          value: 0.15,
          elementalTypes: ['Flame'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Flame'],
        },
      ],
      critRateBuffs: [],
    },
    ['Nemesis']: {
      id: 'Nemesis',
      displayName: 'Nemesis',
      elementalType: 'Volt',
      type: 'Support',
      attackPercentBuffs: [
        {
          id: 'Volt Resonance',
          displayName: 'Volt Resonance',
          description: '+15% volt ATK when equipping 2 or more volt weapons',
          value: 0.15,
          elementalTypes: ['Volt'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Volt'],
        },
        {
          id: 'Volt Benediction',
          displayName: 'Volt Benediction',
          description:
            "+5% entire team's volt ATK by 5% when Benediction Resonance is active",
          value: 0.05,
          elementalTypes: ['Volt'],
          canStack: true,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          weaponResonanceRequirements: ['Benediction'],
        },
        {
          id: 'Nemesis 5*',
          displayName: 'Nemesis 5*',
          description: '+10% ATK for having 1 electrode out',
          value: 0.1,
          elementalTypes: ['Altered', 'Flame', 'Frost', 'Physical', 'Volt'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 5,
          maxStarRequirement: 5,
        },
        {
          id: 'Nemesis 6*',
          displayName: 'Nemesis 6*',
          description: '+15% ATK for having 2 electrode out',
          value: 0.15,
          elementalTypes: ['Altered', 'Flame', 'Frost', 'Physical', 'Volt'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 6,
          maxStarRequirement: 6,
        },
      ],
      critRateBuffs: [],
    },
    ['Rubilia']: {
      id: 'Rubilia',
      displayName: 'Rubilia',
      elementalType: 'Volt',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Volt Resonance',
          displayName: 'Volt Resonance',
          description: '+15% volt ATK when equipping 2 or more volt weapons',
          value: 0.15,
          elementalTypes: ['Volt'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Volt'],
        },
      ],
      critRateBuffs: [],
    },
    ['Ruby']: {
      id: 'Ruby',
      displayName: 'Ruby',
      elementalType: 'Flame',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Flame Resonance',
          displayName: 'Flame Resonance',
          description: '+15% flame ATK when equipping 2 or more flame weapons',
          value: 0.15,
          elementalTypes: ['Flame'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Flame'],
        },
        {
          id: 'Ultimate Heat',
          displayName: 'Ultimate Heat',
          description: 'Ultimate Heat gives +10% flame ATK after fully stacked',
          value: 0.1,
          elementalTypes: ['Flame'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 0,
          maxStarRequirement: 6,
        },
      ],
      critRateBuffs: [],
    },
    ['Saki Fuwa']: {
      id: 'Saki Fuwa',
      displayName: 'Saki Fuwa',
      elementalType: 'Frost',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Frost Resonance',
          displayName: 'Frost Resonance',
          description: '+15% frost ATK when equipping 2 or more frost weapons',
          value: 0.15,
          elementalTypes: ['Frost'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Frost'],
        },
      ],
      critRateBuffs: [],
    },
    ['Samir']: {
      id: 'Samir',
      displayName: 'Samir',
      elementalType: 'Volt',
      type: 'DPS',
      attackPercentBuffs: [],
      critRateBuffs: [],
    },
    ['Shiro']: {
      id: 'Shiro',
      displayName: 'Shiro',
      elementalType: 'Physical',
      type: 'DPS',
      attackPercentBuffs: [],
      critRateBuffs: [],
    },
    ['Tian Lang']: {
      id: 'Tian Lang',
      displayName: 'Tian Lang',
      elementalType: 'Volt',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Volt Resonance',
          displayName: 'Volt Resonance',
          description: '+15% volt ATK when equipping 2 or more volt weapons',
          value: 0.15,
          elementalTypes: ['Volt'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Volt'],
        },
        {
          id: 'Volt sense',
          displayName: 'Volt sense',
          description:
            '+6% volt ATK for each other volt weapons equipped. (The tool only assumes 1 other volt weapon)',
          value: 0.06,
          elementalTypes: ['Volt'],
          canStack: false,
          isActivePassively: false,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Volt'],
        },
      ],
      critRateBuffs: [],
    },
    ['Tsubasa']: {
      id: 'Tsubasa',
      displayName: 'Tsubasa',
      elementalType: 'Frost',
      type: 'DPS',
      attackPercentBuffs: [],
      critRateBuffs: [],
    },
    ['Umi']: {
      id: 'Umi',
      displayName: 'Umi',
      elementalType: 'Physical',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Physical Resonance',
          displayName: 'Physical Resonance',
          description:
            '+15% physical ATK when equipping 2 or more physical weapons',
          value: 0.15,
          elementalTypes: ['Physical'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Physical'],
        },
      ],
      critRateBuffs: [],
    },
    ['Yu Lan']: {
      id: 'Yu Lan',
      displayName: 'Yu Lan',
      elementalType: 'Frost',
      type: 'DPS',
      attackPercentBuffs: [
        {
          id: 'Frost Resonance',
          displayName: 'Frost Resonance',
          description: '+15% frost ATK when equipping 2 or more frost weapons',
          value: 0.15,
          elementalTypes: ['Frost'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Frost'],
        },
      ],
      critRateBuffs: [],
    },
    ['Zero']: {
      id: 'Zero',
      displayName: 'Zero',
      elementalType: 'Flame',
      type: 'Support',
      attackPercentBuffs: [
        {
          id: 'Flame Resonance',
          displayName: 'Flame Resonance',
          description: '+15% flame ATK when equipping 2 or more flame weapons',
          value: 0.15,
          elementalTypes: ['Flame'],
          canStack: false,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          elementalResonanceRequirements: ['Flame'],
        },
        {
          id: 'Flame Benediction',
          displayName: 'Flame Benediction',
          description:
            "+5% entire team's flame ATK by 5% when Benediction Resonance is active",
          value: 0.05,
          elementalTypes: ['Flame'],
          canStack: true,
          isActivePassively: true,
          minStarRequirement: 0,
          maxStarRequirement: 6,
          weaponResonanceRequirements: ['Benediction'],
        },
      ],
      critRateBuffs: [],
    },
  },
};

export type WeaponType = 'DPS' | 'Support' | 'Defense';
