import { GearConfig, GearName, GearVersion, StatName } from '../src/types';

const {
  Helmet,
  Eyepiece,
  Spaulders,
  Gloves,
  Bracers,
  Armor,
  CombatEngine,
  Belt,
  Legguards,
  Boots,
  Exoskeleton,
  Microreactor,
} = GearName;

const {
  AlteredAttack,
  AlteredResistance,
  AlteredResistancePercent,
  Attack,
  Crit,
  CritRatePercent,
  FlameAttack,
  FlameAttackPercent,
  FlameDamagePercent,
  FlameResistance,
  FlameResistancePercent,
  FrostAttack,
  FrostAttackPercent,
  FrostDamagePercent,
  FrostResistance,
  FrostResistancePercent,
  HP,
  HPPercent,
  PhysicalAttack,
  PhysicalAttackPercent,
  PhysicalDamagePercent,
  PhysicalResistance,
  PhysicalResistancePercent,
  Resistance,
  VoltAttack,
  VoltAttackPercent,
  VoltDamagePercent,
  VoltResistance,
  VoltResistancePercent,
} = StatName;

const { v1, v2 } = GearVersion;

export const gearConfigs: GearConfig[] = [
  {
    name: Helmet,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
    ],
    version: v1,
  },
  {
    name: Eyepiece,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      HPPercent,
      CritRatePercent,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      AlteredAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
      AlteredResistance,
      PhysicalAttackPercent,
      FlameAttackPercent,
      FrostAttackPercent,
      VoltAttackPercent,
      PhysicalResistancePercent,
      FrostResistancePercent,
      FlameResistancePercent,
      VoltResistancePercent,
      AlteredResistancePercent,
    ],
    version: v1,
  },
  {
    name: Spaulders,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
    ],
    version: v1,
  },
  {
    name: Gloves,
    availableStatNames: [
      HP,
      Crit,
      Attack,
      Resistance,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
    ],
    version: v1,
  },
  {
    name: Bracers,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
    ],
    version: v1,
  },
  {
    name: Armor,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
    ],
    version: v1,
  },
  {
    name: CombatEngine,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      HPPercent,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
      PhysicalAttackPercent,
      FlameAttackPercent,
      FrostAttackPercent,
      VoltAttackPercent,
      PhysicalResistancePercent,
      FrostResistancePercent,
      FlameResistancePercent,
      VoltResistancePercent,
      PhysicalDamagePercent,
      FlameDamagePercent,
      FrostDamagePercent,
      VoltDamagePercent,
    ],
    version: v2,
  },
  {
    name: Belt,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
    ],
    version: v1,
  },
  {
    name: Legguards,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
    ],
    version: v1,
  },
  {
    name: Boots,
    availableStatNames: [
      HP,
      Crit,
      Attack,
      Resistance,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
    ],
    version: v1,
  },
  {
    name: Exoskeleton,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      HPPercent,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
      PhysicalAttackPercent,
      FlameAttackPercent,
      FrostAttackPercent,
      VoltAttackPercent,
      PhysicalResistancePercent,
      FrostResistancePercent,
      FlameResistancePercent,
      VoltResistancePercent,
      PhysicalDamagePercent,
      FlameDamagePercent,
      FrostDamagePercent,
      VoltDamagePercent,
    ],
    version: v2,
  },
  {
    name: Microreactor,
    availableStatNames: [
      HP,
      Attack,
      Resistance,
      HPPercent,
      PhysicalAttack,
      FrostAttack,
      FlameAttack,
      VoltAttack,
      PhysicalResistance,
      FrostResistance,
      FlameResistance,
      VoltResistance,
      PhysicalAttackPercent,
      FlameAttackPercent,
      FrostAttackPercent,
      VoltAttackPercent,
      PhysicalResistancePercent,
      FrostResistancePercent,
      FlameResistancePercent,
      VoltResistancePercent,
      PhysicalDamagePercent,
      FlameDamagePercent,
      FrostDamagePercent,
      VoltDamagePercent,
    ],
    version: v2,
  },
];
