import { GearType } from './types';

export const gearTypes: GearType[] = [
  {
    name: 'Helmet',
    inGameName: 'Helm',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
    ],
    version: '1.0',
  },
  {
    name: 'Eyepiece',
    inGameName: 'Eyepiece',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'HP %',
      'Crit Rate %',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Altered Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
      'Altered Resistance',
      'Physical Attack %',
      'Flame Attack %',
      'Frost Attack %',
      'Volt Attack %',
      'Physical Resistance %',
      'Frost Resistance %',
      'Flame Resistance %',
      'Volt Resistance %',
      'Altered Resistance %',
    ],
    version: '1.0',
  },
  {
    name: 'Spaulders',
    inGameName: 'Spaulders',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
    ],
    version: '1.0',
  },
  {
    name: 'Gloves',
    inGameName: 'Handguards',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Crit',
      'Attack',
      'Resistance',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
    ],
    version: '1.0',
  },
  {
    name: 'Bracers',
    inGameName: 'Bracers',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
    ],
    version: '1.0',
  },
  {
    name: 'Armor',
    inGameName: 'Armor',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
    ],
    version: '1.0',
  },
  {
    name: 'Combat Engine',
    inGameName: 'Combat Engine',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'HP %',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
      'Physical Attack %',
      'Flame Attack %',
      'Frost Attack %',
      'Volt Attack %',
      'Physical Resistance %',
      'Frost Resistance %',
      'Flame Resistance %',
      'Volt Resistance %',
      'Physical Damage %',
      'Flame Damage %',
      'Frost Damage %',
      'Volt Damage %',
    ],
    version: '2.0',
  },
  {
    name: 'Belt',
    inGameName: 'Belt',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
    ],
    version: '1.0',
  },
  {
    name: 'Legguards',
    inGameName: 'Legguards',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
    ],
    version: '1.0',
  },
  {
    name: 'Boots',
    inGameName: 'Sabatons',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Crit',
      'Attack',
      'Resistance',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
    ],
    version: '1.0',
  },
  {
    name: 'Exoskeleton',
    inGameName: 'Exoskeleton',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'HP %',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
      'Physical Attack %',
      'Flame Attack %',
      'Frost Attack %',
      'Volt Attack %',
      'Physical Resistance %',
      'Frost Resistance %',
      'Flame Resistance %',
      'Volt Resistance %',
      'Physical Damage %',
      'Flame Damage %',
      'Frost Damage %',
      'Volt Damage %',
    ],
    version: '2.0',
  },
  {
    name: 'Microreactor',
    inGameName: 'Microreactor',
    numberOfRandomStats: 4,
    possibleRandomStatTypeNames: [
      'HP',
      'Attack',
      'Resistance',
      'HP %',
      'Physical Attack',
      'Frost Attack',
      'Flame Attack',
      'Volt Attack',
      'Physical Resistance',
      'Frost Resistance',
      'Flame Resistance',
      'Volt Resistance',
      'Physical Attack %',
      'Flame Attack %',
      'Frost Attack %',
      'Volt Attack %',
      'Physical Resistance %',
      'Frost Resistance %',
      'Flame Resistance %',
      'Volt Resistance %',
      'Physical Damage %',
      'Flame Damage %',
      'Frost Damage %',
      'Volt Damage %',
    ],
    version: '2.0',
  },
];
