import { StatType } from './types';

export const statTypes: StatType[] = [
  {
    name: 'Altered Attack',
    inGameName: 'Altered Attack',
    role: 'Attack',
    elementalType: 'Altered',
    iconImageName: 'altered-attack.png',
  },
  {
    name: 'Altered Resistance',
    inGameName: 'Altered Resistance',
    role: 'Resistance',
    elementalType: 'Altered',
    iconImageName: 'altered-res.png',
  },
  {
    name: 'Altered Resistance %',
    inGameName: 'Altered Resistance',
    role: 'Resistance %',
    elementalType: 'Altered',
    isPercentageBased: true,
    iconImageName: 'altered-res.png',
  },
  {
    name: 'Attack',
    inGameName: 'Attack',
    role: 'Attack',
    elementalType: 'None',
    iconImageName: 'attack.png',
  },
  {
    name: 'Crit',
    inGameName: 'Crit',
    role: 'Crit',
    elementalType: 'None',
    iconImageName: 'crit.png',
  },
  {
    name: 'Crit Rate %',
    inGameName: 'Crit Rate',
    role: 'Crit %',
    elementalType: 'None',
    isPercentageBased: true,
    iconImageName: 'crit.png',
  },
  {
    name: 'Flame Attack',
    inGameName: 'Flame Attack',
    role: 'Attack',
    elementalType: 'Flame',
    iconImageName: 'flame-attack.png',
  },
  {
    name: 'Flame Attack %',
    inGameName: 'Flame Attack',
    role: 'Attack %',
    elementalType: 'Flame',
    isPercentageBased: true,
    iconImageName: 'flame-attack.png',
  },
  {
    name: 'Flame Damage %',
    inGameName: 'Flame Damage',
    role: 'Damage %',
    elementalType: 'Flame',
    isPercentageBased: true,
    iconImageName: 'flame-attack.png',
  },
  {
    name: 'Flame Resistance',
    inGameName: 'Flame Resistance',
    role: 'Resistance',
    elementalType: 'Flame',
    iconImageName: 'flame-res.png',
  },
  {
    name: 'Flame Resistance %',
    inGameName: 'Flame Resistance',
    role: 'Resistance %',
    elementalType: 'Flame',
    isPercentageBased: true,
    iconImageName: 'flame-res.png',
  },
  {
    name: 'Frost Attack',
    inGameName: 'Frost Attack',
    role: 'Attack',
    elementalType: 'Frost',
    iconImageName: 'frost-attack.png',
  },
  {
    name: 'Frost Attack %',
    inGameName: 'Frost Attack',
    role: 'Attack %',
    elementalType: 'Frost',
    isPercentageBased: true,
    iconImageName: 'frost-attack.png',
  },
  {
    name: 'Frost Damage %',
    inGameName: 'Frost Damage',
    role: 'Damage %',
    elementalType: 'Frost',
    isPercentageBased: true,
    iconImageName: 'frost-attack.png',
  },
  {
    name: 'Frost Resistance',
    inGameName: 'Frost Resistance',
    role: 'Resistance',
    elementalType: 'Frost',
    iconImageName: 'frost-res.png',
  },
  {
    name: 'Frost Resistance %',
    inGameName: 'Frost Resistance',
    role: 'Resistance %',
    elementalType: 'Frost',
    isPercentageBased: true,
    iconImageName: 'frost-res.png',
  },
  {
    name: 'HP',
    inGameName: 'HP',
    role: 'HP',
    elementalType: 'None',
    iconImageName: 'hp.png',
  },
  {
    name: 'HP %',
    inGameName: 'HP',
    role: 'HP %',
    elementalType: 'None',
    isPercentageBased: true,
    iconImageName: 'hp.png',
  },
  {
    name: 'Physical Attack',
    inGameName: 'Physical Attack',
    role: 'Attack',
    elementalType: 'Physical',
    iconImageName: 'attack.png',
  },
  {
    name: 'Physical Attack %',
    inGameName: 'Physical Attack',
    role: 'Attack %',
    elementalType: 'Physical',
    isPercentageBased: true,
    iconImageName: 'attack.png',
  },
  {
    name: 'Physical Damage %',
    inGameName: 'Physical Damage',
    role: 'Damage %',
    elementalType: 'Physical',
    isPercentageBased: true,
    iconImageName: 'attack.png',
  },
  {
    name: 'Physical Resistance',
    inGameName: 'Physical Resistance',
    role: 'Resistance',
    elementalType: 'Physical',
    iconImageName: 'phys-res.png',
  },
  {
    name: 'Physical Resistance %',
    inGameName: 'Physical Resistance',
    role: 'Resistance %',
    elementalType: 'Physical',
    isPercentageBased: true,
    iconImageName: 'phys-res.png',
  },
  {
    name: 'Resistance',
    inGameName: 'Resistance',
    role: 'Resistance',
    elementalType: 'None',
    iconImageName: 'res.png',
  },
  {
    name: 'Volt Attack',
    inGameName: 'Volt Attack',
    role: 'Attack',
    elementalType: 'Volt',
    iconImageName: 'volt-attack.png',
  },
  {
    name: 'Volt Attack %',
    inGameName: 'Volt Attack',
    role: 'Attack %',
    elementalType: 'Volt',
    isPercentageBased: true,
    iconImageName: 'volt-attack.png',
  },
  {
    name: 'Volt Damage %',
    inGameName: 'Volt Damage',
    role: 'Damage %',
    elementalType: 'Volt',
    isPercentageBased: true,
    iconImageName: 'volt-attack.png',
  },
  {
    name: 'Volt Resistance',
    inGameName: 'Volt Resistance',
    role: 'Resistance',
    elementalType: 'Volt',
    iconImageName: 'volt-res.png',
  },
  {
    name: 'Volt Resistance %',
    inGameName: 'Volt Resistance',
    role: 'Resistance %',
    elementalType: 'Volt',
    isPercentageBased: true,
    iconImageName: 'volt-res.png',
  },
];
