import { ElementalType, StatConfig, StatName, StatType } from '../src/types';

export const statConfigs: StatConfig[] = [
  {
    name: StatName.AlteredAttack,
    inGameName: 'Altered Attack',
    range: { base: 69, min: 239, max: 623 },
    type: StatType.Attack,
    elementalType: ElementalType.Altered,
    iconImageName: 'altered-attack.png',
  },
  {
    name: StatName.AlteredResistance,
    inGameName: 'Altered Resistance',
    range: { base: 215, min: 390, max: 974 },
    type: StatType.Resistance,
    elementalType: ElementalType.Altered,
    iconImageName: 'altered-res.png',
  },
  {
    name: StatName.AlteredResistancePercent,
    inGameName: 'Altered Resistance',
    range: { base: 0.0787, min: 0.09, max: 0.09 },
    type: StatType.ResistancePercent,
    elementalType: ElementalType.Altered,
    isPercentageBased: true,
    iconImageName: 'altered-res.png',
  },
  {
    name: StatName.Attack,
    inGameName: 'Attack',
    range: { base: 52, min: 93, max: 234 },
    type: StatType.Attack,
    elementalType: ElementalType.None,
    iconImageName: 'attack.png',
  },
  {
    name: StatName.Crit,
    inGameName: 'Crit',
    range: { base: 258, min: 468, max: 1169 },
    type: StatType.Crit,
    elementalType: ElementalType.None,
    iconImageName: 'crit.png',
  },
  {
    name: StatName.CritRatePercent,
    inGameName: 'Crit Rate',
    range: { base: 0.0105, min: 0.0119, max: 0.0119 },
    type: StatType.CritPercent,
    elementalType: ElementalType.None,
    isPercentageBased: true,
    iconImageName: 'crit.png',
  },
  {
    name: StatName.FlameAttack,
    inGameName: 'Flame Attack',
    range: { base: 69, min: 125, max: 312 },
    type: StatType.Attack,
    elementalType: ElementalType.Flame,
    iconImageName: 'flame-attack.png',
  },
  {
    name: StatName.FlameAttackPercent,
    inGameName: 'Flame Attack',
    range: { base: 0.0126, min: 0.0144, max: 0.0144 },
    type: StatType.AttackPercent,
    elementalType: ElementalType.Flame,
    isPercentageBased: true,
    iconImageName: 'flame-attack.png',
  },
  {
    name: StatName.FlameDamagePercent,
    inGameName: 'Flame Damage',
    range: { base: 0.0065, min: 0.0072, max: 0.0072 },
    type: StatType.DamagePercent,
    elementalType: ElementalType.Flame,
    isPercentageBased: true,
    iconImageName: 'flame-attack.png',
  },
  {
    name: StatName.FlameResistance,
    inGameName: 'Flame Resistance',
    range: { base: 215, min: 390, max: 974 },
    type: StatType.Resistance,
    elementalType: ElementalType.Flame,
    iconImageName: 'flame-res.png',
  },
  {
    name: StatName.FlameResistancePercent,
    inGameName: 'Flame Resistance',
    range: { base: 0.0787, min: 0.09, max: 0.09 },
    type: StatType.ResistancePercent,
    elementalType: ElementalType.Flame,
    isPercentageBased: true,
    iconImageName: 'flame-res.png',
  },
  {
    name: StatName.FrostAttack,
    inGameName: 'Frost Attack',
    range: { base: 69, min: 125, max: 312 },
    type: StatType.Attack,
    elementalType: ElementalType.Frost,
    iconImageName: 'frost-attack.png',
  },
  {
    name: StatName.FrostAttackPercent,
    inGameName: 'Frost Attack',
    range: { base: 0.0126, min: 0.0144, max: 0.0144 },
    type: StatType.AttackPercent,
    elementalType: ElementalType.Frost,
    isPercentageBased: true,
    iconImageName: 'frost-attack.png',
  },
  {
    name: StatName.FrostDamagePercent,
    inGameName: 'Frost Damage',
    range: { base: 0.0065, min: 0.0072, max: 0.0072 },
    type: StatType.DamagePercent,
    elementalType: ElementalType.Frost,
    isPercentageBased: true,
    iconImageName: 'frost-attack.png',
  },
  {
    name: StatName.FrostResistance,
    inGameName: 'Frost Resistance',
    range: { base: 215, min: 390, max: 974 },
    type: StatType.Resistance,
    elementalType: ElementalType.Frost,
    iconImageName: 'frost-res.png',
  },
  {
    name: StatName.FrostResistancePercent,
    inGameName: 'Frost Resistance',
    range: { base: 0.0787, min: 0.09, max: 0.09 },
    type: StatType.ResistancePercent,
    elementalType: ElementalType.Frost,
    isPercentageBased: true,
    iconImageName: 'frost-res.png',
  },
  {
    name: StatName.HP,
    inGameName: 'HP',
    range: { base: 4125, min: 7480, max: 18700 },
    type: StatType.HP,
    elementalType: ElementalType.None,
    iconImageName: 'hp.png',
  },
  {
    name: StatName.HPPercent,
    inGameName: 'HP',
    range: { base: 0.0094, min: 0.0108, max: 0.0108 },
    type: StatType.HPPercent,
    elementalType: ElementalType.None,
    isPercentageBased: true,
    iconImageName: 'hp.png',
  },
  {
    name: StatName.PhysicalAttack,
    inGameName: 'Physical Attack',
    range: { base: 69, min: 125, max: 312 },
    type: StatType.Attack,
    elementalType: ElementalType.Physical,
    iconImageName: 'attack.png',
  },
  {
    name: StatName.PhysicalAttackPercent,
    inGameName: 'Physical Attack',
    range: { base: 0.0126, min: 0.0144, max: 0.0144 },
    type: StatType.AttackPercent,
    elementalType: ElementalType.Physical,
    isPercentageBased: true,
    iconImageName: 'attack.png',
  },
  {
    name: StatName.PhysicalDamagePercent,
    inGameName: 'Physical Damage',
    range: { base: 0.0065, min: 0.0072, max: 0.0072 },
    type: StatType.DamagePercent,
    elementalType: ElementalType.Physical,
    isPercentageBased: true,
    iconImageName: 'attack.png',
  },
  {
    name: StatName.PhysicalResistance,
    inGameName: 'Physical Resistance',
    range: { base: 215, min: 390, max: 974 },
    type: StatType.Resistance,
    elementalType: ElementalType.Physical,
    iconImageName: 'phys-res.png',
  },
  {
    name: StatName.PhysicalResistancePercent,
    inGameName: 'Physical Resistance',
    range: { base: 0.0787, min: 0.09, max: 0.09 },
    type: StatType.ResistancePercent,
    elementalType: ElementalType.Physical,
    isPercentageBased: true,
    iconImageName: 'phys-res.png',
  },
  {
    name: StatName.Resistance,
    inGameName: 'Resistance',
    range: { base: 64, min: 117, max: 292 },
    type: StatType.Resistance,
    elementalType: ElementalType.None,
    iconImageName: 'res.png',
  },
  {
    name: StatName.VoltAttack,
    inGameName: 'Volt Attack',
    range: { base: 69, min: 125, max: 312 },
    type: StatType.Attack,
    elementalType: ElementalType.Volt,
    iconImageName: 'volt-attack.png',
  },
  {
    name: StatName.VoltAttackPercent,
    inGameName: 'Volt Attack',
    range: { base: 0.0126, min: 0.0144, max: 0.0144 },
    type: StatType.AttackPercent,
    elementalType: ElementalType.Volt,
    isPercentageBased: true,
    iconImageName: 'volt-attack.png',
  },
  {
    name: StatName.VoltDamagePercent,
    inGameName: 'Volt Damage',
    range: { base: 0.0065, min: 0.0072, max: 0.0072 },
    type: StatType.DamagePercent,
    elementalType: ElementalType.Volt,
    isPercentageBased: true,
    iconImageName: 'volt-attack.png',
  },
  {
    name: StatName.VoltResistance,
    inGameName: 'Volt Resistance',
    range: { base: 215, min: 390, max: 974 },
    type: StatType.Resistance,
    elementalType: ElementalType.Volt,
    iconImageName: 'volt-res.png',
  },
  {
    name: StatName.VoltResistancePercent,
    inGameName: 'Volt Resistance',
    range: { base: 0.0787, min: 0.09, max: 0.09 },
    type: StatType.ResistancePercent,
    elementalType: ElementalType.Volt,
    isPercentageBased: true,
    iconImageName: 'volt-res.png',
  },
];
